export const dimensionRulesEnum = {
  BIG_CANVAS: 1000,
  SMALL_CANVAS: 600,
  face: {
    SMALL_CANVAS_ADJUSTMENT: 0.4,
    BIG_CANVAS_ADJUSTMENT: 0.3,
    REGULAR_CANVAS_ADJUSTMENT: 0.45
  },
  document: {
    SMALL_CANVAS_ADJUSTMENT: 0.65,
    BIG_CANVAS_ADJUSTMENT: 0.55,
    REGULAR_CANVAS_ADJUSTMENT: 0.6
  }
}
