const yooComponents = {
  YooAnimation: () => import('./atoms/Animation/Animation.vue'),
  YooAvatar: () => import('./atoms/Avatar/Avatar.vue'),
  YooButton: () => import('./atoms/Button/Button.vue'),
  YooButtonToggle: () => import('./molecules/ButtonToggle/ButtonToggle.vue'),
  YooCheckButton: () => import('./atoms/CheckButton/CheckButton.vue'),
  YooIcon: () => import('./atoms/Icon/Icon.vue'),
  YooSelectDate: () => import('./atoms/SelectDate/SelectDate.vue'),
  YooStepper: () => import('./atoms/Stepper/Stepper.vue'),
  YooSwitch: () => import('./atoms/Switch/Switch.vue'),
  YooListItem: () => import('./molecules/ListItem/ListItem.vue'),
  YooFormGroup: () => import('./molecules/FormGroup/FormGroup.vue'),
  YooHeader: () => import('./molecules/Header/Header.vue'),
  YooModal: () => import('./molecules/Modal/Modal.vue'),
  YooNotify: () => import('./molecules/Notify/Notify.vue'),
  YooPagination: () => import('./molecules/Pagination/Pagination.vue'),
  YooCard: () => import('./molecules/Card/Card.vue'),
  YooQuizQuestion: () => import('./molecules/QuizQuestion/QuizQuestion.vue'),
  YooSelectButton: () => import('./molecules/SelectButton/SelectButton.vue'),
  YooSegmentedBar: () => import('./molecules/SegmentedBar/SegmentedBar.vue'),
  YooTableAttribute: () => import('./molecules/TableAttribute/TableAttribute.vue'),
  YooFlexLayout: () => import('./bosons/FlexLayout/FlexLayout.vue'),
  YooGridLayout: () => import('./bosons/GridLayout/GridLayout.vue'),
  YooIndicator: () => import('./quarks/Indicator/Indicator.vue'),
  YooScrollView: () => import('./bosons/ScrollView/ScrollView.vue'),
  YooInfiniteScroll: () => import('./bosons/InfiniteScroll/InfiniteScroll.vue'),
  ThemeProvider: () => import('./bosons/ThemeProvider/ThemeProvider.vue')
}

export default yooComponents
