name: deploy

on:
  create:
    tags:
      - release-*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # GET TAG VERSION IN $GITHUB_ENV
      - name: Get TAG_VERSION
        run: echo "TAG_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      # CHECKOUT REPOSITORY
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: main
      # SETUP NODE ENV W/ NPM PUBLIC REGISTRY
      - name: Setup Node Env
        uses: actions/setup-node@v2
        with:
          registry-url: 'https://registry.npmjs.org'
      # CONFIGURE GIT
      - name: Configure Git
        run: |
          git config user.name github-ci
          git config user.email gabriel.mule@cyberlabs.ai
      # RUN SCRIPTS
      - name: Update package version
        run: node "./ci.js" ${{ env.TAG_VERSION }}
      - name: Build VueJS Package
        run: |
          npm install
          npm run build:vue
      - name: Prepare "npm" folder to deploy
        run: |
          rm -rf npm
          mkdir npm
          mkdir npm/vue
          cp -fR dist/vue/* npm/vue
          cp README.md npm/vue/README.md
          cp package.json npm/package.json
          cp package.json npm/vue/package.json
          rm -rf dist
      - name: Prepare "package.json" Files
        run: |
          node -e "let pkg=require('./npm/package.json'); pkg.main='/vue/yoo.common.js'; require('fs').writeFileSync('./npm/package.json', JSON.stringify(pkg, null, 2));"
          node -e "let pkg=require('./npm/vue/package.json'); pkg.main='/yoo.common.js'; require('fs').writeFileSync('./npm/vue/package.json', JSON.stringify(pkg, null, 2));"
      # PREPARE PUBLISH
      - name: Enter prepared npm folder
        run: |
          cd npm
      # ADD & COMMIT CHANGES
      - name: Add & Commit Changes
        run: |
          git add .
          git commit -am "[github-ci] Published Version"
          git push origin main:npm --force
      # TAG VERSION
      - name: Tag Version
        run: |
          git tag -a ${{ env.TAG_VERSION }} -m ${{ env.TAG_VERSION }} --force
          git push --tags --force
      # ENTER VUE FOLDER
      - name: Prepare VueJS Publish
        run: |
          cd npm
          cd vue
      # PUBLISH VUE PACKAGE
      - name: Publish VueJS Package
        run: npm publish npm/vue/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      # SUCCESS MESSAGE TO  DISCORD
      - name: Success Message to Discord
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.WEBHOOK_URL }}
          title: "Published ${{ env.TAG_VERSION }}"
          description: |
            A new release has been published:
            [Click here to go to the release page](https://github.com/Yoonit-Labs/vue-yoonit-components/releases/tag/${{ env.TAG_VERSION }})
          color: 0x00ff00
          username: GitHub Actions
