name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Installing dependencies
        run: |
          Installing dependencies...,
          npm install
          
      - name: Run unit tests
        run: |
          Running unit tests...,
          npm run test:unit
